services:
  postgres:
    image: postgres:15
    container_name: local_postgres
    restart: always
    environment:
      POSTGRES_USER: localuser
      POSTGRES_PASSWORD: localpass
      POSTGRES_DB: localdb
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  api:
    build: .
    container_name: catfacts_api
    restart: always
    volumes:
      - ./migrations:/src/migrations
      - ./src:/src/src
      - ./alembic.ini:/src/alembic.ini
      - ./.env:/src/.env
    depends_on:
      - postgres
    env_file:
      - .env
    environment:
      PORT: 8000
    ports:
      - "8000:8000"
    command: >
      uvicorn src.main:app
      --host 0.0.0.0
      --port ${PORT:-8000}

volumes:
  pgdata:
